### ISSUE TITLE
SliderDemo script initializes dots incorrectly

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion-examples/LeapMotionCoreAssets#140]
When the DemoSlider is set to a data binder that has a value different than .5, the slider dots are positioned incorrectly (based on the slider button rather than the slider line:

![_thumb_18100](https://cloud.githubusercontent.com/assets/2576138/10375231/2de14de8-6dac-11e5-86c4-3e7a01d0f66f.png)

This can be fixed in the SliderDemo.cs class Awake() function. For some reason, the dots are initially parented to the current game object (the one containing DemoScroll). When set up the same as the DemoScroll widget, this game object is the slider button. The calculations that compute the dot's initial position are performed, based on the current parent. The dots are then reparented to the slider button's parent (the top level slider object in the prefab).

Broken code:

        for (float x = lower_limit + increments / 2.0f; x < upper_limit; x += increments)
        {
          GameObject new_dot = Instantiate(dot) as GameObject;
          new_dot.transform.parent = transform;
          new_dot.transform.localPosition = new Vector3(x, 1.0f, m_localTriggerDistance);
          new_dot.transform.localRotation = dot.transform.localRotation;
          new_dot.transform.localScale = Vector3.one;
          new_dot.transform.parent = transform.parent;
          dots.Add(new_dot);
        }

Fixed code:

        for (float x = lower_limit + increments / 2.0f; x < upper_limit; x += increments)
        {
          GameObject new_dot = Instantiate(dot) as GameObject;
          new_dot.transform.parent = transform.parent; //Fix!
          new_dot.transform.localPosition = new Vector3(x, 1.0f, m_localTriggerDistance);
          new_dot.transform.localRotation = dot.transform.localRotation;
          new_dot.transform.localScale = Vector3.one;
          // new_dot.transform.parent = transform.parent; now redundant
          dots.Add(new_dot);
        }

**Comment by derekfc** [comment]
Hi - 2 ??'s / proposed corrections: 
Do you mean SliderDemo.cs, instead of DemoScroll.cs (as that is where we found matching code) related to the Slider?
Also, do you mean as the fix:  "new_dot.transform.parent = transform.parent;"  instead?

With those 2 adjustments, it worked great for us.  Thanks for your attention to this!

**Comment by jo3w4rd** [comment]
Fixed.  Thanks! (Too much coffee or not enough...)
