### ISSUE TITLE
Debug Log spew when using VR_WORLD_VR_HANDS configuration

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion-examples/LeapMotionCoreAssets#146]
When you set the VR_WORLD_VR_HANDS configuration in the HMR configuration manager, the LeapCameraAlignment._latestImageTimestamp property getter constantly spews "Could not calculate valid timestamp. Returning 0." to the debug console. This is a spurious warning since images aren't used in this configuration.

**Comment by peroht** [comment]
Will this warning be removed or not? Always annyoing with false warnings...

**Comment by peroht** [comment]
Any news on this? It is more than annoying.
